name: linting, testing, building
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  pipeline:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install --force
      - run: npm install --force ts-node
      - run: npm run build:prod
        if: always()
      - run: npm run lint:ts
        if: always()
      - run: npm run lint:scss
        if: always()
      - run: npm run test:unit
        if: always()
      - run: npm run test:ui:ci
        if: always()