name: linting, testing, building
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm install --force
      - run: npm run build:prod
      - run: lint:ts
      - run: lint:scss
      - run: test:unit