name: linting, testing, building
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build:prod
      - run: lint:ts
      - run: lint:scss
      - run: test:unit

      # "start": "webpack serve --env port=3000",
      # "build:prod": "webpack --env mode=production",
      # "build:dev": "webpack --env mode=development",
      # "lint:ts": "eslint \"**/*.{ts,tsx}\"",
      # "lint:ts:fix": "eslint \"**/*.{ts,tsx}\" --fix",
      # "lint:scss": "npx stylelint \"**/*.scss\"",
      # "lint:scss:fix": "npx stylelint \"**/*.scss\" --fix",
      # "test:unit": "jest --config ./config/jest/jest.config.ts --env=jsdom",
      # "test:ui": "npx loki test",
      # "storybook": "storybook dev -p 6006 -c ./config/storybook",
      # "build-storybook": "storybook build -c ./config/storybook"